Repository AlexKiselich/adopt-dont-shop, pull requests merged in 2023-05, with the labels that each got.

#11 Created a pull request template
  pull_request_template.md
Labels: feature

#13 3 2 starting an application
  app/controllers/application_controller.rb
  app/controllers/applications_controller.rb
  app/views/application/show.html.erb
  app/views/applications/new.html.erb
  app/views/applications/show.html.erb
  app/views/applications/welcome.html.erb
  app/views/pets/index.html.erb
  config/routes.rb
  db/migrate/20230519022540_create_applications.rb
  db/schema.rb
  spec/features/applications/application_spec.rb
  spec/features/applications/new_spec.rb
  spec/features/applications/show_spec.rb
  spec/features/pets/index_spec.rb
Labels: user story, feature, test

#14 Updated the application welcome view to the proper file
  app/views/application/welcome.html.erb
Labels: bug

#15 4 3 starting an application form not completed
  app/controllers/applications_controller.rb
  app/models/application.rb
  app/views/applications/new.html.erb
  app/views/pets/index.html.erb
  doc/user_stories.md
  spec/features/applications/new_spec.rb
  spec/features/pets/index_spec.rb
  spec/features/shelters/create_spec.rb
Labels: user story, test

#16 Finished User story 4
  app/controllers/applications_controller.rb
  app/views/applications/show.html.erb
  doc/user_stories.md
  spec/features/applications/show_spec.rb
Labels: user story, test

#17 6 5 add a pet to an application
  app/controllers/applications_controller.rb
  app/models/application.rb
  app/views/applications/show.html.erb
  config/routes.rb
  spec/features/applications/show_spec.rb
Labels: user story, feature, test

#18 7 6 submit an application
  app/controllers/applications_controller.rb
  app/views/applications/show.html.erb
  doc/user_stories.md
  spec/features/applications/show_spec.rb
Labels: user story, feature, test

#19 8 7 no pets on an application
  app/views/applications/show.html.erb
  app/views/layouts/application.html.erb
  doc/user_stories.md
  spec/features/applications/show_spec.rb
Labels: user story, feature, test

#40 20 8 partial matches for pet names
  spec/features/applications/show_spec.rb
Labels: user story, feature, test

#41 Complete US9
  spec/features/applications/show_spec.rb
Labels: user story, feature, test

#42 Complete US10
  app/controllers/admin_controller.rb
  app/models/shelter.rb
  app/views/admin/index.html.erb
  config/routes.rb
  spec/features/admin/shelters/index_spec.rb
  spec/models/application_spec.rb
  spec/models/shelter_spec.rb
Labels: user story, feature, test

#43 23 11 shelters with pending applications
  app/controllers/admin_controller.rb
  app/controllers/application_pets_controller.rb
  app/models/shelter.rb
  app/views/admin/index.html.erb
  config/routes.rb
  spec/features/admin/shelters/index_spec.rb
  spec/features/applications/show_spec.rb
  spec/models/shelter_spec.rb
Labels: user story, model, feature, test

#44 Test setup
  doc/user_stories.md
  spec/features/admin/applications/show_spec.rb
Labels: user story, test

#46 24 12 approving a pet for adoption
  app/controllers/admin/applications_controller.rb
  app/controllers/admin/shelters_controller.rb
  app/controllers/admin_controller.rb
  app/views/admin/applications/show.html.erb
  app/views/admin/shelters/index.html.erb
  config/routes.rb
  doc/user_stories.md
  spec/features/admin/applications/show_spec.rb
  spec/features/admin/shelters/index_spec.rb
Labels: user story, feature, test

#47 25 13 rejecting a pet for adoption
  app/controllers/admin/applications_controller.rb
  app/models/shelter.rb
  app/views/admin/applications/show.html.erb
  db/migrate/20230523173308_add_status_to_application_pets.rb
  db/schema.rb
  spec/features/admin/applications/show_spec.rb
Labels: user story, feature, test

#48 Completed User story 14
  app/controllers/admin/applications_controller.rb
  app/views/admin/applications/show.html.erb
  spec/features/admin/applications/show_spec.rb
Labels: user story, feature, test

#49 Refactor
  app/controllers/admin/applications_controller.rb
  app/controllers/application_pets_controller.rb
  app/controllers/applications_controller.rb
  app/models/shelter.rb
  app/views/admin/applications/show.html.erb
  app/views/applications/new.html.erb
  app/views/applications/show.html.erb
  app/views/shelters/_form.html.erb
  app/views/shelters/edit.html.erb
  app/views/shelters/new.html.erb
  config/routes.rb
  db/seeds.rb
  doc/user_stories.md
  spec/features/admin/applications/show_spec.rb
  spec/features/applications/new_spec.rb
  spec/features/applications/show_spec.rb
  spec/features/pets/index_spec.rb
Labels: bug, user story, model, feature, test

#50 Refactoring
  app/controllers/admin/applications_controller.rb
  app/controllers/admin/shelters_controller.rb
  app/controllers/application_controller.rb
  app/controllers/applications_controller.rb
  app/controllers/pets_controller.rb
  app/controllers/shelters_controller.rb
  app/models/application.rb
  app/views/admin/applications/show.html.erb
  app/views/applications/new.html.erb
  app/views/shelters/new.html.erb
  config/routes.rb
  spec/features/admin/applications/show_spec.rb
  spec/features/applications/application_spec.rb
  spec/features/applications/new_spec.rb
  spec/features/applications/show_spec.rb
  spec/models/application_pet_spec.rb
  spec/models/application_spec.rb
  spec/models/shelter_spec.rb
Labels: user story, model, feature, test

#51 Remove redundant file
  app/controllers/application_pets_controller.rb
Labels: bug
